name: release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'yarn.lock'

permissions: {}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '20.x'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
        run: |
          yarn
          yarn release
